<?php

namespace Slovotepec\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150414121718 extends AbstractMigration
{
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE newsletter_subscription (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, subscribed_on DATETIME NOT NULL, unsubscribed_on DATETIME DEFAULT NULL, unsubscribe_hash VARCHAR(255) DEFAULT NULL, INDEX IDX_A82B55ADE7927C74 (email), INDEX IDX_A82B55AD4B1EFC02 (active), INDEX IDX_A82B55AD513B2E8B (unsubscribe_hash), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
	}

	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE newsletter_subscription");
	}
}
