<?php

namespace Herecsrymy\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151007081421 extends AbstractMigration
{
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");

		$this->addSql("CREATE SEQUENCE location_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE TABLE location (id INT NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, point point DEFAULT NULL, PRIMARY KEY(id))");
		$this->addSql("COMMENT ON COLUMN location.point IS '(DC2Type:point)'");

		$this->addSql("INSERT INTO location (id, name, address, point) SELECT nextval('location_id_seq'), '', location, location_point FROM event");

		$this->addSql("ALTER TABLE event ADD location_id INT DEFAULT NULL");
		$this->addSql("ALTER TABLE event DROP location");
		$this->addSql("ALTER TABLE event DROP location_point");
		$this->addSql("ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA764D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("CREATE INDEX IDX_3BAE0AA764D218E ON event (location_id)");
	}

	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");

		$this->addSql("CREATE SCHEMA public");
		$this->addSql("ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA764D218E");
		$this->addSql("DROP SEQUENCE location_id_seq CASCADE");
		$this->addSql("DROP TABLE location");
		$this->addSql("DROP INDEX IDX_3BAE0AA764D218E");
		$this->addSql("ALTER TABLE event ADD location VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE event ADD location_point point DEFAULT NULL");
		$this->addSql("ALTER TABLE event DROP location_id");
		$this->addSql("COMMENT ON COLUMN event.location_point IS '(DC2Type:point)'");
	}
}
