<?php

namespace Herecsrymy\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150508144136 extends AbstractMigration
{
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
		
		$this->addSql("CREATE SEQUENCE attachment_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE category_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE event_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE file_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE newsletter_subscription_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE post_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE user_account_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE TABLE attachment (id INT NOT NULL, post_id INT NOT NULL, name VARCHAR(255) NOT NULL, type SMALLINT NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_795FD9BB4B89032C ON attachment (post_id)");
		$this->addSql("CREATE TABLE category (id INT NOT NULL, title VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, description VARCHAR(255) DEFAULT NULL, published BOOLEAN NOT NULL, sort SMALLINT NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_64C19C15124F222 ON category (sort)");
		$this->addSql("CREATE TABLE event (id INT NOT NULL, name VARCHAR(255) NOT NULL, note VARCHAR(255) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, location_point point DEFAULT NULL, tickets_price SMALLINT NOT NULL, tickets_link VARCHAR(255) NOT NULL, facebook_url VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_3BAE0AA793F3C6CA ON event (datetime)");
		$this->addSql("COMMENT ON COLUMN event.location_point IS '(DC2Type:point)'");
		$this->addSql("CREATE TABLE file (id INT NOT NULL, attachment_id INT NOT NULL, file_name VARCHAR(255) NOT NULL, file_type VARCHAR(32) NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_8C9F3610464E68B ON file (attachment_id)");
		$this->addSql("CREATE TABLE newsletter_subscription (id INT NOT NULL, email VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, subscribed_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, unsubscribed_on TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, unsubscribe_hash VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_A82B55ADE7927C74 ON newsletter_subscription (email)");
		$this->addSql("CREATE INDEX IDX_A82B55AD4B1EFC02 ON newsletter_subscription (active)");
		$this->addSql("CREATE INDEX IDX_A82B55AD513B2E8B ON newsletter_subscription (unsubscribe_hash)");
		$this->addSql("CREATE TABLE post (id INT NOT NULL, category_id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, text TEXT NOT NULL, published BOOLEAN NOT NULL, published_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_5A8A6C8D12469DE2 ON post (category_id)");
		$this->addSql("CREATE TABLE user_account (id INT NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_253B48AEE7927C74 ON user_account (email)");
		$this->addSql("ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB4B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE file ADD CONSTRAINT FK_8C9F3610464E68B FOREIGN KEY (attachment_id) REFERENCES attachment (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
	}

	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
		
		$this->addSql("CREATE SCHEMA public");
		$this->addSql("ALTER TABLE file DROP CONSTRAINT FK_8C9F3610464E68B");
		$this->addSql("ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8D12469DE2");
		$this->addSql("ALTER TABLE attachment DROP CONSTRAINT FK_795FD9BB4B89032C");
		$this->addSql("DROP SEQUENCE attachment_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE category_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE event_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE file_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE newsletter_subscription_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE post_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE user_account_id_seq CASCADE");
		$this->addSql("DROP TABLE attachment");
		$this->addSql("DROP TABLE category");
		$this->addSql("DROP TABLE event");
		$this->addSql("DROP TABLE file");
		$this->addSql("DROP TABLE newsletter_subscription");
		$this->addSql("DROP TABLE post");
		$this->addSql("DROP TABLE user_account");
	}
}
