<?php

namespace Slovotepec\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150329192255 extends AbstractMigration
{
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE category ADD sort SMALLINT NOT NULL");
		$this->addSql("CREATE INDEX IDX_64C19C15124F222 ON category (sort)");
	}

	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP INDEX IDX_64C19C15124F222 ON category");
		$this->addSql("ALTER TABLE category DROP sort");
	}
}
