<?php

namespace Herecsrymy\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150827222029 extends AbstractMigration
{
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");

		$this->addSql("ALTER TABLE event ADD published BOOLEAN DEFAULT 'true' NOT NULL");
		$this->addSql("CREATE INDEX IDX_3BAE0AA793F3C6CA683C6017 ON event (datetime, published)");
		$this->addSql("CREATE INDEX IDX_3BAE0AA7683C6017 ON event (published)");
	}

	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");

		$this->addSql("CREATE SCHEMA public");
		$this->addSql("DROP INDEX IDX_3BAE0AA793F3C6CA683C6017");
		$this->addSql("DROP INDEX IDX_3BAE0AA7683C6017");
		$this->addSql("ALTER TABLE event DROP published");
	}
}
