<?php

namespace Slovotepec\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150329122125 extends AbstractMigration
{
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE attachment (id INT AUTO_INCREMENT NOT NULL, post_id INT NOT NULL, name VARCHAR(255) NOT NULL, type SMALLINT NOT NULL, INDEX IDX_795FD9BB4B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, description VARCHAR(255) DEFAULT NULL, published TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE file (id INT AUTO_INCREMENT NOT NULL, attachment_id INT NOT NULL, file_name VARCHAR(255) NOT NULL, file_type VARCHAR(32) NOT NULL, INDEX IDX_8C9F3610464E68B (attachment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE post (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, published TINYINT(1) NOT NULL, published_on DATETIME NOT NULL, INDEX IDX_5A8A6C8D12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB4B89032C FOREIGN KEY (post_id) REFERENCES post (id)");
		$this->addSql("ALTER TABLE file ADD CONSTRAINT FK_8C9F3610464E68B FOREIGN KEY (attachment_id) REFERENCES attachment (id)");
		$this->addSql("ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)");
	}

	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE file DROP FOREIGN KEY FK_8C9F3610464E68B");
		$this->addSql("ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8D12469DE2");
		$this->addSql("ALTER TABLE attachment DROP FOREIGN KEY FK_795FD9BB4B89032C");
		$this->addSql("DROP TABLE attachment");
		$this->addSql("DROP TABLE category");
		$this->addSql("DROP TABLE file");
		$this->addSql("DROP TABLE post");
	}
}
