<?php

namespace JiriHraje\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150131114202 extends AbstractMigration
{
	public function up(Schema $schema)
	{
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
		
		$this->addSql("CREATE SEQUENCE concert_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE image_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE post_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE album_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE SEQUENCE song_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
		$this->addSql("CREATE TABLE concert (id INT NOT NULL, name VARCHAR(140) NOT NULL, note VARCHAR(255) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, location_point point DEFAULT NULL, tickets_price SMALLINT NOT NULL, tickets_link VARCHAR(255) NOT NULL, facebook_url VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX i_datetime ON concert (datetime)");
		$this->addSql("COMMENT ON COLUMN concert.location_point IS '(DC2Type:point)'");
		$this->addSql("CREATE TABLE image (id INT NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE TABLE post (id INT NOT NULL, title VARCHAR(140) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, text TEXT NOT NULL, published BOOLEAN NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_5A8A6C8D93F3C6CA ON post (datetime)");
		$this->addSql("CREATE TABLE album (id INT NOT NULL, cover_id INT NOT NULL, title VARCHAR(140) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_39986E43922726E9 ON album (cover_id)");
		$this->addSql("CREATE INDEX IDX_39986E4393F3C6CA ON album (datetime)");
		$this->addSql("CREATE TABLE song (id INT NOT NULL, album_id INT DEFAULT NULL, title VARCHAR(140) NOT NULL, album_position SMALLINT DEFAULT NULL, published DATE NOT NULL, soundcloud_url VARCHAR(255) NOT NULL, duration SMALLINT NOT NULL, note VARCHAR(255) DEFAULT NULL, lyrics TEXT NOT NULL, PRIMARY KEY(id))");
		$this->addSql("CREATE INDEX IDX_33EDEEA11137ABCF ON song (album_id)");
		$this->addSql("ALTER TABLE album ADD CONSTRAINT FK_39986E43922726E9 FOREIGN KEY (cover_id) REFERENCES image (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE song ADD CONSTRAINT FK_33EDEEA11137ABCF FOREIGN KEY (album_id) REFERENCES album (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
	}

	public function down(Schema $schema)
	{
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
		
		$this->addSql("CREATE SCHEMA public");
		$this->addSql("ALTER TABLE album DROP CONSTRAINT FK_39986E43922726E9");
		$this->addSql("ALTER TABLE song DROP CONSTRAINT FK_33EDEEA11137ABCF");
		$this->addSql("DROP SEQUENCE concert_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE image_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE post_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE album_id_seq CASCADE");
		$this->addSql("DROP SEQUENCE song_id_seq CASCADE");
		$this->addSql("DROP TABLE concert");
		$this->addSql("DROP TABLE image");
		$this->addSql("DROP TABLE post");
		$this->addSql("DROP TABLE album");
		$this->addSql("DROP TABLE song");
	}
}
